version: "3.8"

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    environment:
      - TZ=Europe/Paris
      - VPN_SERVICE_PROVIDER=$(VPN_SERVICE_PROVIDER) # e.g., "mullvad", "nordvpn", etc.
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES:-Netherlands} # Optional: preferred country
      - OPENVPN_ENCRYPTION=256 # Optional: set encryption strength
    cap_add:
      - NET_ADMIN # Required for VPN container to manage network
    volumes:
      - ${CONFIG_PATH}/gluetun:/gluetun # Gluetun config storage
    ports:
      - 6881:6881   # qBittorrent TCP (through VPN)
      - 6881:6881/udp # qBittorrent UDP (through VPN)
      - 8989:8989   # Sonarr (through VPN)
      - 7878:7878   # Radarr (through VPN)
      - 9696:9696   # Prowlarr (through VPN)
      - 8081:8081   # qBittorrent WebUI (through VPN)
      - 6789:6789   # NZBGet (through VPN)
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun" # Shares network with gluetun (VPN)
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=8081 # Web UI port
    volumes:
      - ${CONFIG_PATH}/qbittorrent:/config # qBittorrent config
      - ${DATA_PATH}/downloads:/downloads  # Downloaded files
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget
    container_name: nzbget
    network_mode: "service:gluetun" # Shares network with gluetun (VPN)
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${CONFIG_PATH}/nzbget:/config # NZBGet config
      - ${DATA_PATH}/downloads:/downloads # Downloaded files
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    network_mode: "service:gluetun" # Shares network with gluetun (VPN)
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${CONFIG_PATH}/radarr:/config # Radarr config
      - ${DATA_PATH}/movies:/movies   # Movies library
      - ${DATA_PATH}/downloads:/downloads # Downloaded files
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    network_mode: "service:gluetun" # Shares network with gluetun (VPN)
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${CONFIG_PATH}/sonarr:/config # Sonarr config
      - ${DATA_PATH}/tv:/tv           # TV library
      - ${DATA_PATH}/downloads:/downloads # Downloaded files
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    network_mode: "service:gluetun" # Shares network with gluetun (VPN)
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${CONFIG_PATH}/prowlarr:/config # Prowlarr config
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096 # Jellyfin web interface (direct, not through VPN)
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${CONFIG_PATH}/jellyfin:/config # Jellyfin config
      - ${DATA_PATH}/media:/media       # Media library
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    ports:
      - 3579:3579 # Jellyseerr web interface (direct, not through VPN)
    environment:
      - TZ=Europe/Paris
    volumes:
      - ${CONFIG_PATH}/jellyseerr:/app/config # Jellyseerr config
    restart: unless-stopped

# Environment variables required:
# CONFIG_PATH=/path/to/config
# DATA_PATH=/path/to/data
# VPN_SERVICE_PROVIDER, OPENVPN_USER, OPENVPN_PASSWORD, etc.